### ISSUE TITLE
Microsoft Azure CreateQueue using Simple REST Client

### ISSUE THREAD

**Issue by vinay-khurana** [CI-WATER/TethysCluster#10]
(Hello, I'm new to GitHub. If this is not a good place to raise this type of issue, please redirect me.)

I'm trying to create a queue on Azure cloud. I've an Azure account, namespace and using Service Bus. Due to some restrictions I need to do it using RAW GET/PUT requests so I'm using Simple REST Client.
[Simple REST client: https://chrome.google.com/webstore/detail/simple-rest-client/fhjcajmcbmldlhcimfajhfbgofnpcjmb?utm_source=chrome-ntp-icon]

![azure_request_response](https://cloud.githubusercontent.com/assets/14837300/10101771/40229a78-63b8-11e5-96e0-48f0d5397b56.PNG)

HmacSha256 encoding the string "PUT\n\n\n\n0\n\n\n\n\n\n\n\nx-ms-date:Fri, 25 Sep 2015 03:16:12 GMT\nx-ms-version:2009-09-19\n/mynamespace-ns" with secret key is the SharedAccessKey copied from Connection Information page on Azure Portal. After that Base64Encode the resulted string.

Every-time I send the request I got the following response:

401MalformedToken: Invalid authorization header: The request is missing WRAP authorization credentials. TrackingId:8d52cae0-0dba-470d-8db2-3e76d4fd4d0b_G27,TimeStamp:9/25/2015 9:45:17 AM

**Comment by sdc50** [comment]
K-V-Coder, 

I'm not sure that this is the right place for this issue. TethysCluster is a Python library that uses the the Azure Python to provision VMs and configure them with HTCondor. It does not directly use the Azure REST api, nor does it use a service bus. I recommend looking at Azure support options for help with this: https://azure.microsoft.com/en-us/support/options/.
